#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: mlkem-c-embedded
  description: mlkem-c-embedded
  homepage: https://github.com/pq-code-package/mlkem-c-embedded
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
